apiVersion: v1
kind: Service
metadata:
  name: {{ include "medical-pdf-summarizer.fullname" . }}
  labels:
    {{- include "medical-pdf-summarizer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "evalhttp" }}
      protocol: TCP
      name: evalhttp
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "medical-pdf-summarizer.selectorLabels" . | nindent 4 }}
